version: "3.2"
services:
  php:
    build:
      context: .
    image: webuxmotion/hi-eddy:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=hi-eddy-mysql-app
      - MYSQL_USER=hi-eddyuser
      - MYSQL_PASSWORD=hi-eddypass
      - MYSQL_DB=hi-eddy_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "60001:80"
    container_name: hi-eddy-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=hi-eddyuser
      - MYSQL_PASSWORD=hi-eddypass
      - MYSQL_DATABASE=hi-eddy_db
    container_name: hi-eddy-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "60002:80"
    environment:
      - PMA_HOST=hi-eddy-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: hi-eddy-phpmyadmin-app
networks:
  frontend:
  backend: